//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_pgsql.dataModel
{
    using entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class userEntities : DbContext
    {
        public userEntities()
            : base(contextwrapper.CreateInstance("dataModel.profuser", "Host=localhost;Database=iristest;Username=postgres;Password=tpstps_1;"))
           //: base("name=userEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<profile> profiles { get; set; }
    }
}
